modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="http://github.com/coolsimulations/infinity-water-bucket/issues/"
logoFile="logo.png"
license="All rights reserved"

[[mods]]
    modId="infinitywaterbucket"
    version="${version}"
    updateJSONURL="https://coolsimulations.net/mcmods/infinity-water-bucket/versionchecker.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/infinity-water-bucket"
    displayName="Infinity Water Bucket"
    credits="Thanks to alkyaLy for establishing the foundations of this mod!"
    authors="coolsim, alkyaLy"
    description='''
    Allows the enchantment Infinity for Water Buckets, providing an infinite portable water source
    '''
[[dependencies.infinitywaterbucket]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.20,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitywaterbucket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitywaterbucket]]
    modId="milkallthemobs"
    mandatory=false
    versionRange="[1.5,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitywaterbucket]]
    modId="getinthebucket"
    mandatory=false
    versionRange="[3.0.7,]"
    ordering="NONE"
    side="BOTH"
[[dependencies.infinitywaterbucket]]
    modId="cavesandcliffs"
    mandatory=false
    versionRange="[1.16.5-7.2.0,]"
    ordering="NONE"
    side="BOTH"
    